import type { Todo } from "@/types/todo"

export const mockTodos: Todo[] = [
  {
    id: "1",
    title: "Completar presentación del proyecto",
    description: "Preparar slides y ensayar la presentación para el cliente del viernes",
    completed: false,
    createdAt: new Date("2024-01-15"),
    dueDate: new Date("2024-01-20"),
    category: "Trabajo",
    tags: ["urgente", "presentación"],
  },
  {
    id: "2",
    title: "Comprar ingredientes para la cena",
    description: "Lista: pollo, verduras, arroz, especias",
    completed: true,
    createdAt: new Date("2024-01-14"),
    dueDate: new Date("2024-01-16"),
    category: "Compras",
    tags: ["comida", "supermercado"],
  },
  {
    id: "3",
    title: "Revisar código del nuevo feature",
    description: "Hacer code review del pull request #234",
    completed: false,
    createdAt: new Date("2024-01-13"),
    dueDate: new Date("2024-01-18"),
    category: "Trabajo",
    tags: ["desarrollo", "review"],
  },
  {
    id: "4",
    title: "Llamar al dentista",
    description: "Agendar cita para limpieza dental",
    completed: false,
    createdAt: new Date("2024-01-12"),
    dueDate: new Date("2024-01-17"),
    category: "Salud",
    tags: ["cita", "salud"],
  },
  {
    id: "5",
    title: "Leer capítulo 5 del libro de React",
    description: "Continuar con el aprendizaje de hooks avanzados",
    completed: false,
    createdAt: new Date("2024-01-11"),
    category: "Educación",
    tags: ["lectura", "programación"],
  },
  {
    id: "6",
    title: "Organizar escritorio",
    description: "Limpiar y organizar el espacio de trabajo",
    completed: true,
    createdAt: new Date("2024-01-10"),
    category: "Hogar",
    tags: ["limpieza", "organización"],
  },
  {
    id: "7",
    title: "Actualizar CV",
    description: "Agregar nuevas habilidades y experiencias recientes",
    completed: false,
    createdAt: new Date("2024-01-09"),
    dueDate: new Date("2024-01-15"),
    category: "Personal",
    tags: ["carrera", "documentos"],
  },
  {
    id: "8",
    title: "Planificar vacaciones de verano",
    description: "Investigar destinos y hacer reservaciones",
    completed: false,
    createdAt: new Date("2024-01-08"),
    category: "Personal",
    tags: ["vacaciones", "planificación"],
  },
]
